dist: xenial

language: python

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
    - PROJINST=$HOME/gdalinstall
    - PROJBUILD=$HOME/projbuild

jobs:
  include:
    - python: "3.7"
      env:
        GDALVERSION="2.4.4"
        PROJVERSION="4.9.3"

services:
  - postgresql

addons:
  apt:
    packages:
      - devscripts
      - libhdf5-serial-dev
      - libgdal-dev
      - libatlas-dev
      - libatlas-base-dev
      - gfortran
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
 
before_install:
  - sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get -qq update
  - sudo apt-get install gdal-bin libgdal-dev -y
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - gdal-config --version
  - gdalinfo --version
 
install:
  - pip install .
  - pip install gdal==`gdal-config --version`
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls

script:
  - python3 tests.py

after_success:
  - coveralls

cache:
  directories:
    - $GDALINST
    - ~/.cache/pip
