dist: xenial
language: python
python:
  - "3.7"
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - devscripts
      - libgdal-dev
      - libproj-dev
      - libgeos-dev
      - libudunits2-dev
      - libnetcdf-dev
      - netcdf-bin
before_install:
  - sudo apt-get install python-gdal
install: 
  - pip install .
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
script:
  - python3 obia4rtm/tests.py
after_success:
  - coveralls
