dist: xenial
language: python
python:
  - "3.7"
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - devscripts
before_install:
  - sudo apt-get install gdal python3-gdal
install: 
  - pip install .
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
script:
  - python3 tests.py
after_success:
  - coveralls
